package com.bmc.buenacocina.core

const val LOCATION_COLLECTION_NAME = "delivery-locations"
const val PAYMENT_METHOD_COLLECTION_NAME = "payment-types"
const val PRODUCT_FAVORITE_COLLECTION_NAME = "product-favorites"
const val STORE_FAVORITE_COLLECTION_NAME = "store-favorites"
const val PRODUCT_REVIEW_COLLECTION_NAME = "product-reviews"
const val PRODUCT_COLLECTION_NAME = "products"
const val SHOPPING_CART_COLLECTION_NAME = "shopping-carts"
const val SHOPPING_CART_SUB_COLLECTION_NAME = "shopping-cart-items"
const val ORDER_COLLECTION_NAME = "orders"
const val ORDER_SUB_COLLECTION_NAME = "order-lines"
const val STORE_REVIEW_COLLECTION_NAME = "store-reviews"
const val STORE_COLLECTION_NAME = "stores"
const val USER_COLLECTION_NAME = "users"
const val USER_SUB_COLLECTION_TOKEN = "tokens"
const val SHARED_PREFERENCES_FILE_NAME = "sec_preferences"
const val API_URL = "/buena-cocina-fp/us-central1/api"
const val ROOM_DATABASE_NAME = "local_room_database"
const val PAGING_PAGE_SIZE = 3
const val PAGING_PREFETCH_DISTANCE = 0
const val PAGING_INITIAL_LOAD_SIZE = 5
const val SEARCH_PAGING_PAGE_SIZE = 10
const val PRODUCT_REVIEW_MINIMUM_COMMENT_LENGTH = 10
const val PRODUCT_REVIEW_MAXIMUM_COMMENT_LENGTH = 200
const val STORE_REVIEW_MINIMUM_COMMENT_LENGTH = 10
const val STORE_REVIEW_MAXIMUM_COMMENT_LENGTH = 200
const val OK_HTTP_CLIENT_CONNECTION_TIMEOUT_IN_SEC = 20L
const val OK_HTTP_CLIENT_WRITE_TIMEOUT_IN_SEC = 20L
const val OK_HTTP_CLIENT_READ_TIMEOUT_IN_SEC = 20L
const val SHARING_COROUTINE_TIMEOUT_IN_SEC = 5L
const val ORDER_STATUS_CREATED_LEVEL = 0
const val ORDER_STATUS_ACTIVE_LEVEL = 1
const val ORDER_STATUS_PROGRESS_LEVEL = 2
const val ORDER_STATUS_ON_WAY_LEVEL = 3
const val ORDER_STATUS_DELIVERED_LEVEL = 4
const val ORDER_STATUS_ERROR_LEVEL = 5
const val ORDER_STATUS_UNASSIGNED_LEVEL = 6
const val ORDER_STATUS_CREATED_NAME = "Creado"
const val ORDER_STATUS_ACTIVE_NAME = "Activo"
const val ORDER_STATUS_PROGRESS_NAME = "En progreso"
const val ORDER_STATUS_ON_WAY_NAME = "En camino"
const val ORDER_STATUS_DELIVERED_NAME = "Entregado"
const val ORDER_STATUS_ERROR_NAME = "Error"
const val ORDER_STATUS_UNASSIGNED_NAME = ""
