package com.bmc.buenacocina.core

enum class ReviewSentimentStatus(val status: String) {
    VERY_NEGATIVE(REVIEW_SENTIMENT_VERY_NEGATIVE_NAME),
    NEGATIVE(REVIEW_SENTIMENT_NEGATIVE_NAME),
    NEUTRAL(REVIEW_SENTIMENT_NEUTRAL_NAME),
    POSITIVE(REVIEW_SENTIMENT_POSITIVE_NAME),
    VERY_POSITIVE(REVIEW_SENTIMENT_VERY_POSITIVE_NAME),
    UNASSIGNED(REVIEW_SENTIMENT_UNASSIGNED_NAME)
}